// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBTuea9hOafKqGgp5X18SqmsO8AjTgEz8',
    appId: '1:152725630980:web:c6be3a4195e6ef64a30551',
    messagingSenderId: '152725630980',
    projectId: 'flutterfire-ui-codelab-e1a70',
    authDomain: 'flutterfire-ui-codelab-e1a70.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-e1a70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqkdYifDYxp0Asy5o94GOSKjApoTyzhOQ',
    appId: '1:152725630980:android:2170a7ee42f6bf67a30551',
    messagingSenderId: '152725630980',
    projectId: 'flutterfire-ui-codelab-e1a70',
    storageBucket: 'flutterfire-ui-codelab-e1a70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALEldfymLHvoGDd69n_inkYg8mSyyBqpg',
    appId: '1:152725630980:ios:29032c51178d9b58a30551',
    messagingSenderId: '152725630980',
    projectId: 'flutterfire-ui-codelab-e1a70',
    storageBucket: 'flutterfire-ui-codelab-e1a70.appspot.com',
    iosBundleId: 'com.example.gruppoSera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALEldfymLHvoGDd69n_inkYg8mSyyBqpg',
    appId: '1:152725630980:ios:29032c51178d9b58a30551',
    messagingSenderId: '152725630980',
    projectId: 'flutterfire-ui-codelab-e1a70',
    storageBucket: 'flutterfire-ui-codelab-e1a70.appspot.com',
    iosBundleId: 'com.example.gruppoSera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBTuea9hOafKqGgp5X18SqmsO8AjTgEz8',
    appId: '1:152725630980:web:e94ca5b1576c73fda30551',
    messagingSenderId: '152725630980',
    projectId: 'flutterfire-ui-codelab-e1a70',
    authDomain: 'flutterfire-ui-codelab-e1a70.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-e1a70.appspot.com',
  );
}
